### ISSUE TITLE
Feature calculation: GC Content

### ISSUE THREAD

**Issue by Finesim97** [OstfriesenBI/PredmiRNA#10]
R function:
Input: csv file with the sequences:
```
"comment","sequence","realmiRNA"
"mmu-mir-380 MI0000797 Mus musculus miR-380 stem-loop","AAGAUG",1
"mmu-mir-381 MI0000798 Mus musculus miR-381 stem-loop","AAUUC",1
```
Output: csv file with the sequence identifier and the GC content
```
"comment","gccont"
"mmu-mir-380 MI0000797 Mus musculus miR-380 stem-loop",0.3333
"mmu-mir-381 MI0000798 Mus musculus miR-381 stem-loop",0,2
```
This function already does part of the work, only [seqinr](https://www.rdocumentation.org/packages/seqinr/versions/3.4-5/topics/G%2BC%20Content) needs to be installed.

**Comment by mariusrueve** [comment]
Result can be found in dc7c485.
