### ISSUE TITLE
Feature calculation: Dinucleotid frequencies

### ISSUE THREAD

**Issue by Finesim97** [OstfriesenBI/PredmiRNA#11]
R function:
Input: csv file with the sequences:
```
"comment","sequence","realmiRNA"
"mmu-mir-380 MI0000797 Mus musculus miR-380 stem-loop","AAGAUG",1
"mmu-mir-381 MI0000798 Mus musculus miR-381 stem-loop","AAUUC",1
```
Output: csv file with the sequence identifier and the frequencies of the 16 different dinucleotid frequencies
```
"comment",aa,ac,ag,at,ca, ... 
"mmu-mir-380 MI0000797 Mus musculus miR-380 stem-loop", ...
"mmu-mir-381 MI0000798 Mus musculus miR-381 stem-loop", ...
```
This function already does part of the work, only [seqinr](https://www.rdocumentation.org/packages/seqinr/versions/3.4-5/topics/count) needs to be installed.
``` R
count(seq, 2,freq=T)
```

Source Paper:
De novo SVM classification of precursor microRNAs from genomic pseudo hairpins using global and intrinsic folding measures

**Comment by mariusrueve** [comment]
Still a problem in c5269bc but can't figure out how to solve it right now.

**Comment by mariusrueve** [comment]
Solved the last Problem. Now trying to find an elegant way to write those results to a .csv file.
