### ISSUE TITLE
Feature calculation: Stacking triplets

### ISSUE THREAD

**Issue by Finesim97** [OstfriesenBI/PredmiRNA#15]
R/Python function:
Input: csv file with the sequences and the secondary structure:
```
"comment","sequence","realmiRNA","secstructure",
"mmu-mir-380 MI0000797 Mus musculus miR-380 stem-loop","AAGAUG",1,"...(.."
"mmu-mir-381 MI0000798 Mus musculus miR-381 stem-loop","AAUUC",1,"...(.."
```
Source paper:
Classification of real and pseudo microRNA precursors using local structure-sequence features and support vector machine
See figure 1 and 2. 

The best features seem to be the A(((, U(((, G((( and C((( triplets, but the calculation of all 32 variants would be nice.

**Comment by mariusrueve** [comment]
## [Paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1360673/)

### Figure1:
![image](https://user-images.githubusercontent.com/44000950/52699135-5aa5b880-2f75-11e9-9017-a2b11878eeb2.png)

### Figure2:
![image](https://user-images.githubusercontent.com/44000950/52699169-6d1ff200-2f75-11e9-93ed-6bd2576b8eef.png)
