### ISSUE TITLE
Feature calculation: MFEI3

### ISSUE THREAD

**Issue by mariusrueve** [OstfriesenBI/PredmiRNA#23]
### [MFE Index 3 (MFEI3)](https://academic.oup.com/bioinformatics/article/25/8/989/324698)
`MFEI3 = dG/n _loops`
- dG/L: Gibbs free energy divided by the length of the sequence
- n_loops: the number of loops in the secondary structure

Input: csv file with MFE/L and n_loops
```
"comment","dG/sequencelength","n_loops"
"test","-29.90/24","1"
```

Output: csv file with comment & mfei3
```
"comment","mfei3"
"test","xxx"
```

**Comment by Finesim97** [comment]
The number of loops should be derived from the secondary structure. I am not sure, how you get the number of loops from it:
....((((((..(((((..((((((..(((.((.....)).))))))))))))))....))))))............((((((......)))))).

**Comment by mariusrueve** [comment]
If [amount of (] == [amount of )] the loop is closed and loops+1. Therefore we maybe need an extra script to count the loops, if we don't find another solution.
