### ISSUE TITLE
Feature calculation: MFEI4

### ISSUE THREAD

**Issue by mariusrueve** [OstfriesenBI/PredmiRNA#24]
### [MFE Index 4 (MFEI4)](https://academic.oup.com/bioinformatics/article/25/8/989/324698)
 `MFEI4 = MFE/tot_bases`
- MFE: minimum free energy
- tot_base: total numbers of base pairs in the secondary structure

Input: csv file with MFE and tot_base
```
"comment","mfe","tot_base"
"test","-29.90","12"
```

Output: csv file with comment & mfei4
```
"comment","mfei4"
"test","xxx"
```

**Comment by Finesim97** [comment]
When i read it correctly , you have to just count the number paired bases in the secondary structure: The ( or the ):
....((((((..(((((..((((((..(((.((.....)).))))))))))))))....))))))............((((((......)))))).
