### ISSUE TITLE
Feature calculation: NEFE

### ISSUE THREAD

**Issue by mariusrueve** [OstfriesenBI/PredmiRNA#25]
### [Normalized Ensemble Free Energy (NEFE)](https://academic.oup.com/bioinformatics/article/25/8/989/324698)

- `Z = e^[-F/(kT)]` F is the free energy
- `EFE = -RT ln(Z)` EFE is the Ensemble free energy
- `NEFE = EFE/L` L is the sequence length

Input: csv file ...
````
````
Output: csv file ...
````
````

**Comment by Finesim97** [comment]
We can get the ensemble energy from rnafold, i will add a new issue for that.
