### ISSUE TITLE
Feature calculation: Frequency of the MFE structure (Freq)

### ISSUE THREAD

**Issue by mariusrueve** [OstfriesenBI/PredmiRNA#27]
### [Frequency of the MFE structure (Freq)](https://academic.oup.com/bioinformatics/article/25/8/989/324698)
`Freq = e^((EFE - MFE)/RT`
- EFE: Ensemble free energy
- MFE: Minimum free energy

Input: csv file with EFE, MFE
````
"comment","EFE","MFE"
"test","-22.30","-20.40"
````
Output: csv file with Freq
````
"comment","Freq"
"test","xxx"
````

**Comment by Finesim97** [comment]
The frequency of the of secondary structure is also produced by RNAfold or an adjacent tool.
