### ISSUE TITLE
Script/Program: Split csv file

### ISSUE THREAD

**Issue by Finesim97** [OstfriesenBI/PredmiRNA#6]
To enable parallel processing, the input csv files have to be split. The script (python, R, java, bash, awk) takes 1 csv file as an input and splits it into a given number of csv output files and stores them in a given folder:
`csvsplit input.csv 200 outputdir/ `
Would generate outputdir/0.csv outputdir/1.csv ... outputdir/199.csv.
Every file has to start with the same header line as the one in the input file.

**Comment by mariusrueve** [comment]
Currently I have a problem finding a solution to get the "header" into every single .csv and to give a output directory. d1cf283

**Comment by mariusrueve** [comment]
Final result and comments in 5f0f246.
